### ISSUE TITLE
Allow for errors to be displayed on page when WP_DEBUG_DISPLAY is set to true.

### ISSUE THREAD

**Issue by stuartshields** [humanmade/hm-platform#13]
With `WP_DEBUG` to `true` and `define( 'WP_DEBUG_DISPLAY', true );`, set we currently don't allow for the errors to be displayed on page.

We need to patch https://github.com/humanmade/hm-platform/blob/e80ff9797d48137f14e92860863894a4cee5a148/load.php#L10 to allow for the function to parse the first argument sent to it.

**Comment by joehoyle** [comment]
Oops! I think you saying that we hook the filter, but the function returns `null`, therefore you can't use the `enable_wp_debug_mode_checks` filter?

**Comment by rmccue** [comment]
The default value being filtered is `true`. We don't return, so it ends up as `null`, and hence that whole section is never run; i.e. we're actually overriding the default behaviour altogether.
