### ISSUE TITLE
How to address alloptions bug and Redis

### ISSUE THREAD

**Issue by nathanielks** [humanmade/hm-platform#132]
Unfortunately wp-redis [isn't going to accept fixes](https://github.com/pantheon-systems/wp-redis/pull/157#issuecomment-266444418) that address WordPress' `alloptions` bug. The question now is how do we address it? We could fork wp-redis and essentially do the same as we did with our Memcached plugin, or we could go the [VIP route](https://core.trac.wordpress.org/ticket/31245#comment:57) for simplicity. I believe we've had conversations about this in the past, but I wanted to open a ticket for posterity. I very much appreciate the simplicity of VIP's route, but can see where people would be upset with performance implications. Perhaps we ship that first and then write the "proper" integration afterwards?

**Comment by nathanielks** [comment]
@joehoyle

**Comment by joehoyle** [comment]
I'm happy with the VIP sledgehammer approach, atleast in the meantime!

**Comment by nathanielks** [comment]
Sounds good to me!
