### ISSUE TITLE
No-op postmeta_form_keys to return empty array

### ISSUE THREAD

**Issue by joehoyle** [humanmade/hm-platform#14]
This is an annoying part of Core that does a super slow query for pre-populating the form fields with any existing meta keys, however this gets _very_ slow on sites with a lot of meta in the meta table. 

We should probably just disable this by:

```php
add_action( 'postmeta_form_keys', '__return_empty_array' );
```

**Comment by rmccue** [comment]
Can we just remove the metabox instead? There's no good use for it.

```php
add_action( 'add_meta_boxes', function () {
    remove_meta_box( 'postcustom', null, 'normal' );
});
```
