### ISSUE TITLE
Cannot use wp_debug_mode mode and debug constants.

### ISSUE THREAD

**Issue by afilippovsigma** [humanmade/hm-platform#16]
@joehoyle @rmccue Because the `bootstrap` function returns ***null***, the [`wp_debug_mode` function](https://github.com/WordPress/WordPress/blob/master/wp-includes/load.php#L316) always forces to exit before debug constants are checking (see `wp-includes/load.php` line 316-318 as for 4.8.1 WP version) .

I'm wondering if returning `true`  for the `bootstrap` function is the best fix.

**Comment by joehoyle** [comment]
@afilippovsigma thanks for flagging, I've made a commit to master, could you update and let me know if it work now?

Thanks!

**Comment by afilippovsigma** [comment]
@joehoyle Yeah, works fine. Many thanks!
