### ISSUE TITLE
Release version update to reflect code on master

### ISSUE THREAD

**Issue by Japh** [humanmade/hm-platform#166]
My assumption is that code on `master` is `stable` and reflective of the latest version.

Could we please get the CHANGELOG updated and a tagged release of version 1.4.2 out so we can notify development teams to update client stacks?

Seems this version will include some fixes for particular Cavalcade fatal errors too.

cc/ @electrokat

**Comment by nathanielks** [comment]
@Japh 	master is reflective of 1.4.1, there haven't been any changes since?

**Comment by nathanielks** [comment]
More clearly, the latest commit on master _is_ the 1.4.1 release, so there aren't any unreleased commits that I'm seeing.

**Comment by Japh** [comment]
Ah yeah, my bad. I was looking at a project that was attached to master but obviously hadn't been updated. Was weird.

ANYWAY!
