### ISSUE TITLE
Update aws-xray submoudule

### ISSUE THREAD

**Issue by ntwb** [humanmade/hm-platform#174]
The latest hm-platform release currently doesn't include the latest aws-xray changes https://github.com/humanmade/hm-platform/commits/master

The most recent commit of aws-xray to hm-platform is [aws-xray @ f447b53](https://github.com/humanmade/aws-xray/tree/f447b53c86de1b28011b86de4a6ac4ce4babec27) and there are 12 newer commits since the `f447b53` commit https://github.com/humanmade/aws-xray/commits/master

In particular I'm looking to get https://github.com/humanmade/aws-xray/commit/e9512c1e4387f6145b3a0a69bfcb087fb6d012e7 from https://github.com/humanmade/aws-xray/pull/43 into an updated release of _hm-platform_

**Comment by owaincuvelier** [comment]
@ntwb would you be willing to open a PR?

**Comment by ntwb** [comment]
Yes, will do later today

**Comment by Nikschavan** [comment]
@owaincuvelier, @ntwb Submitted a PR #177 to update the `aws-xray` submodule
