### ISSUE TITLE
Add final filtered query into X-Ray

### ISSUE THREAD

**Issue by Nikschavan** [humanmade/hm-platform#183]
Same as https://github.com/humanmade/altis-cloud/issues/183 but for hm-platform

The query that is sent to X-Ray contains placeholders, Also it is possible that the final query can be modified with the filter `query` which we are not accounting for.

The placeholders also increase the size of the final database query and cause https://github.com/humanmade/aws-xray/issues/74

In our case, one of the longest queries is ~120KB which does not get sent to X-Ray. If the placeholders are removed the query is reduced to ~40kb.

**Comment by joehoyle** [comment]
What is this 40KB query?!

**Comment by rmccue** [comment]
Users-by-role query (@Nikschavan is looking into potentially using roles-as-taxonomies in the future).

**Comment by Nikschavan** [comment]
Fixed as #184 is now merged
