### ISSUE TITLE
Add members only.

### ISSUE THREAD

**Issue by owaincuvelier** [humanmade/hm-platform#22]
https://github.com/humanmade/members

**Comment by owaincuvelier** [comment]
Todo: update fork to master

**Comment by joehoyle** [comment]
@owaincuvelier what's the latest here?

**Comment by owaincuvelier** [comment]
@joehoyle on hold, there was some difference of opinion as to whether it should be added. Let me see if I can find where the discussion took place.

**Comment by roborourke** [comment]
@owaincuvelier can you loop me in on the discussion / thinking here? If it happened on slack lets copy that transcript in here, it'd be a part of EK by the looks of it so there's a few other things to do after adding it re. documentation.

**Comment by owaincuvelier** [comment]
This is an old issue, an it's kind lost to the void a little. @roborourke @joehoyle what was the purpose of the members plugin again? Is this to shut off access to staging sites, i.e. private site functionality? 

This only stalled because I cocked up trying to fork the plugin, and never get round to trying again.

**Comment by roborourke** [comment]
I have no idea what the intent was tbh!
