### ISSUE TITLE
Add latest getID3 lib

### ISSUE THREAD

**Issue by roborourke** [humanmade/hm-platform#63]
Right now we have a problem if we're ever going to rely on fetching ID3 tag data through the s3 filestream wrapper.

The version of `getID3` packaged in WP break filestream URIs by replacing double slashes with single so `s3://example` becomes `s3:/example`

Anyone have any issues with that? Will add to `/lib` if not

**Comment by roborourke** [comment]
Of course it could also be added to S3 Uploads, ideally fixed in core though, the ID3 version there is pretty old but the latest requires PHP 5.3 minimum.

**Comment by joehoyle** [comment]
@roborourke where's the code in question that breaks this? Assuming in core - is this part of the WP_Image_Editor abstractions, or done elsewhere?

**Comment by roborourke** [comment]
@joehoyle it's at https://github.com/WordPress/WordPress/blob/master/wp-includes/ID3/getid3.php#L273

Added a core ticket and patch here: https://core.trac.wordpress.org/ticket/43836

Latest master of that lib just has that line commented out :)

**Comment by joehoyle** [comment]
Instead i've added this is s3-uploads at https://github.com/humanmade/S3-Uploads/pull/238, as really I think it's an s3-uploads problem, and anyone using the plugin will also need this fix.

**Comment by roborourke** [comment]
Makes sense! Cheers
