### ISSUE TITLE
Add Composer.json

### ISSUE THREAD

**Issue by paulgibbs** [humanmade/hm-platform#82]
Please consider adding a basic composer.json file. I'm having to pull in updates via Composer's `package` repository type https://getcomposer.org/doc/05-repositories.md#vcs , and it has limitations/annoyances while trying to pull in changes, so even a basic composer.json with the version number in, would help lots.

**Comment by mikeselander** [comment]
Big +1 on this - would be very nice to handle over Composer.

**Comment by fklein-lu** [comment]
👍 from me as well.

**Comment by paulgibbs** [comment]
PR at https://github.com/humanmade/hm-platform/pull/84

**Comment by fklein-lu** [comment]
Fixed via https://github.com/humanmade/hm-platform/commit/723ae8549acca600dd668a0cbee2ca5bce1d086c.

**Comment by paulgibbs** [comment]
FYIs:

I tried adding this to Packagist (subsequently removed), but because HM-Platform uses submodules, Packagist does not copy down the `.git` folder, so you are unable to initialise the submodules. The simple fix is to use it like this:

```
{
	"repositories": [
		{
			"type": "composer",
			"url": "https://wpackagist.org"
		},
		{
			"type": "git",
			"url": "https://github.com/humanmade/hm-platform.git"
		}
	],
	"require-dev": {
	},
	"require": {
		"oomphinc/composer-installers-extender": "~1.1",
		"humanmade/hm-platform": "~1.2",
	},
	"extra": {
		"installer-paths": {
			"{$name}/": [ "type:wordpress-dropin" ]
		}
	}
}
```
